config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root "homes#home"
 get "/home/about" => "homes#about"
 resources :users, only: [:index, :show, :edit, :update]
 resources :books do
  resources :book_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

   validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  attachment :profile_image

  validates :name, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:home, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?



  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = @book.book_comments.new(book_comment_params)
    @comment.user_id = current_user.id
    @comment.save
    @book.book_comments.count
    @comments = @book.book_comments
    # redirect_back(fallback_location: root_path)
  end


  def destroy
    @comment = BookComment.find_by(book_id: params[:book_id], id: params[:id]).destroy
    # redirect_back(fallback_location: root_path)
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if  @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render "index"
    end
  end

  def show
    @sbook = Book.find(params[:id])
    @book = Book.new
    @user = @sbook.user
    @book_comment = BookComment.new
    @comments = @sbook.book_comments
  end

  def edit
    @book = Book.find(params[:id])
    if  @book.user == current_user
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)#どの投稿に結びついているいいねを削除するか
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path
    else
      render "edit"
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_index.html.erb
<table>
  <% comments.each do |comment| %>
    <tr class="body-comment<%= comment.id %>">
      <td>
        <%= link_to user_path(comment.user) do %>
          <%= attachment_image_tag  comment.user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
          <br><%= comment.user.name %>
      </td><% end %>
      <td><%= comment.comment %></td>
      <td><% if comment.user.id == current_user.id %>
            <%= link_to "Destroy", book_book_comment_path(comment.book.id, comment), method: :delete, class:"btn btn-sm btn-danger", remote: true %>
          <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/book_comments/create.js.erb
$(".book<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".body-comment").html("<%= j(render "book_comments/index", comments: @comments) %>");
$("textarea").val("");

app/views/book_comments/destroy.js.erb
$(".body-comment<%= @comment.id %>").remove();

app/views/books/_new.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <label>Title</label>
      <%= f.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <label>Opinion</label>
      <%= f.text_area :body, class:"form-control" %>
  </div>

  <%= f.submit "Create Book", class:"btn btn-success" %>

<% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <div class="errors-text">
        <% if @book.errors.any? %>
        <h3><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h3>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>
      </div>
      <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class:"form-control" %>
        </div>

        <div class="form-group">
          <label>Opinion</label>
          <%= f.text_area :body, class:"form-control" %>
        </div>

          <%= f.submit "Update Book", class:"btn btn-success" %>
      <% end %>

      <p>
        <%= link_to "Show", book_path(@book) %> |
        <%= link_to "Back", books_path %>
      </p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">
  <div class="errors-text">
    <% if @book.errors.any? %>
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
        <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-3">
      <!--プロフィール-->
      <%= render "users/profile", user: @user %>
      <!--新規投稿-->
      <%= render "books/new", book: @book %>
    </div>
    <div class="offset-md-1 col-md-8">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag  book.user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <!--部分テンプ-->
            <td class="favorite-btns<%= book.id %>">
             <%= render "favorites/favorite-btn", book: book %>
            </td>
            <!--部分テンプ-->
            <td><p>コメント数:<%= book.book_comments.count %></p></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice">
  <%if flash[:notice] %>
    <%= flash[:notice]  %>
  <% end %>
</p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <!--プロフィール-->
      <%= render "users/profile", user: @user %>
      <!--新規投稿-->
      <%= render "books/new", book: @book %>
    </div>
    <div class="offset-md-1 col-md-8">
      <h2>Book detail</h2>
      <table class="table">
        <tr class="book<%= @sbook.id %>">
          <td>
            <%= link_to user_path(@sbook.user) do %>
              <%= attachment_image_tag  @sbook.user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
              <br><%= @sbook.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@sbook) do %>
              <%= @sbook.title %>
            <% end %>
          </td>
          <td><%= @sbook.body %></td>
          <!--部分更新だからコントローラ→favorites-->
          <td class="favorite-btn">
            <%= render "favorites/favorite-btn", book: @sbook %>
          </td>
          <!--部分更新だからコントローラ→favorites-->
          <td class ="comments-count">コメント数:<%= @sbook.book_comments.count %></td>
          <% if @sbook.user.id == current_user.id %>
          <td><%= link_to "Edit", edit_book_path(@sbook), class:"btn btn-sm btn-success" %></td>
          <td><%= link_to "Destroy", book_path(@sbook), method: :delete, data: { confirm: "本当に消しますか？" }, class:"btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </table>
      <div class="body-comment">
        <%= render "book_comments/index", comments: @comments %>
      </div>
      <div class="new-comment">
        <%= form_with model:[@sbook, @book_comment],  remote: true do |f| %>
          <%= f.text_area :comment, rows:'150', size:"100" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
  <% if user_signed_in? %>
    <% if book.favorited_by?(current_user) %>
      <p>
        <%= link_to book_favorites_path(book), method: :delete, remote:true do  %>
          <i class="far fa-heart"><%= book.favorites.count %></i>
        <% end %>
      </p>
    <% else %>
      <p>
        <%= link_to book_favorites_path(book), method: :post, remote:true do  %>
          <i class="far fa-heart"><%= book.favorites.count %></i>
        <% end %>
      </p>
    <% end %>
  <% else %>
       <p><i class="far fa-heart"><%= book.favorites.count %></i></p>
  <% end %>

app/views/favorites/create.js.erb
$(".favorite-btns<%= @book.id %>").html("<%= j(render "favorites/favorite-btn", book: @book) %>");
<!--↑一覧　↓詳細-->
$(".favorite-btn").html("<%= j(render "favorites/favorite-btn", book: @book) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btns<%= @book.id %>").html("<%= j(render "favorites/favorite-btn", book: @book) %>");
<!--↑一覧　↓詳細-->
$(".favorite-btn").html("<%= j(render "favorites/favorite-btn", book: @book) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/home.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice]  %></p>
<% end %>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <div class="social">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      </div>

      <div class="social">
        <p>In<i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      </div>

      <p>you can share and exchange your opinions , inpressions , and emotions</p>

      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row" >
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
        </div>

        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path,  class:"btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/30ca97842a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "Bookers", root_path, class:"navbar-brand" %>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

              <li>
                <%= link_to "Home", user_path(current_user.id), class:"nav-link text-light fas fa-home" %>
              </li>

              <li>
                <%= link_to "Users", users_path, class:"nav-link text-light fas fa-users" %>
              </li>


              <li>
                <%= link_to "Books", books_path, class:"nav-link text-light fas fa-book-open" %>
              </li>



              <li>
                <%= link_to "logout", destroy_user_session_path, method: :delete, class:"nav-link text-light fas fa-sign-out-alt" %>
              </li>

            <% else %>

              <li>
                <%= link_to "Home", root_path, class:"nav-link text-light fas fa-home" %>
              </li>



              <li>
                <%= link_to "About", home_about_path, class:"nav-link text-light fas fa-link" %>
              </li>



              <li>
                <%= link_to "sign up", new_user_registration_path, class:"nav-link text-light fas fa-user-plus" %>
              </li>



              <li>
                <%= link_to "login", new_user_session_path, class:"nav-link text-light fas fa-sign-in-alt" %>
              </li>


            <% end %>

        </div>
      </div>
    </div>



    <%= yield %>

    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p col-lg-6>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/users/_profile.html.erb
<h2>User info</h2>
 <%= attachment_image_tag user, :profile_image, size: "60x60", format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <td>name</td>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
  </tbody>
</table>

<!--編集ボタン-->
<!--うまく表示されない-->
<div class="row">
    <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
</div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <div class="errors-text">
        <% if @user.errors.any? %>
          <h3><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <%= form_with model: @user, local:true do |f|%>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <label>Image</label></br>
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="form-group">
          <label>Introduction</label>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container  px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <!--プロフィール-->
      <%= render "users/profile", user: @user %>
      <!--新規投稿-->
      <%= render "books/new", book: @book %>
    </div>
    <div class="offset-md-1 col-md-8">
      <!--8グリッド-->
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
           </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag  user, :profile_image, size: "60x60", fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
        </body>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice">
  <%if flash[:notice] %>
    <%= flash[:notice]  %>
  <% end %>
</p>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <!--プロフィール-->
      <%= render "users/profile", user: @user %>
      <!--新規投稿-->
      <%= render "books/new", book: @book %>
    </div>
    <div class="offset-md-1 col-md-8">


      <h2>Books</h2>
      <!--ここからUser一人Books一覧-->
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag  @user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <td>コメント数:<%= book.book_comments.count %></td>
          </tr>
        <% end %>
        </body>
      </table>
    </div>
  </div>
</div>